name: ai_doctor
description: A Flutter AI Doctor app
version: 1.0.0
environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_dotenv: ^5.1.0
  http: ^1.2.2
  image_picker: ^1.1.2
  url_launcher: ^6.3.0
  google_generative_ai: ^0.2.3
  mime: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - .env